//! 数据模型兼容层
//!
//! 所有模型已迁移至 models_v3.rs，本文件仅保留重新导出以兼容现有代码。
//! 新代码应直接使用 `crate::db::models_v3` 或 `crate::db::ModelName`。

pub use super::models_v3::{
    Story,
    Character,
    Chapter,
    CreateStoryRequest,
    UpdateStoryRequest,
    CreateCharacterRequest,
    CreateChapterRequest,
    User,
    OAuthAccount,
    Session,
    UserInfo,
    ExportTemplate,
    CreateExportTemplateRequest,
    AiOperation,
    CreateAiOperationRequest,
    StoryContract,
    SceneCommit,
    GenesisRun,
    MemoryItem,
    ChapterReadingPower,
    ChaseDebt,
    OverrideContract,
    ReviewIssue,
    GenreProfile,
    Blueprint,
    CreateBlueprintRequest,
    UpdateBlueprintRequest,
    Draft,
    DraftStatus,
    DraftSource,
    Revision,
    RevisionType,
    RevisionStatus,
    PipelineReview,
    ReviewDimension,
    ReviewIssueItem,
    PostProcessRun,
    PostProcessStep,
    PostProcessStatus,
    StepStatus,
    LlmCall,
    RecordLlmCallRequest,
    CharacterState,
};
